# .pre-commit-config.yaml
default_stages: [commit]
repos:
    - repo: https://github.com/aadi308/pre-commit-terraform
      rev: v1.64.1
      hooks:
          - id: terraform_validate
          - id: terraform_tflint
